// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWkXP8Q0KDY5pRAGYxotLOrt4rcGAxs74',
    appId: '1:676079174860:web:18e1366d80ea067ff96e69',
    messagingSenderId: '676079174860',
    projectId: 'carrot-market-clone-2c6e3',
    authDomain: 'carrot-market-clone-2c6e3.firebaseapp.com',
    storageBucket: 'carrot-market-clone-2c6e3.appspot.com',
    measurementId: 'G-ZL9HFPVGQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCahqWRNP8UycldsChVtTz3riYW2NfF27s',
    appId: '1:676079174860:android:e97e5ec99add8696f96e69',
    messagingSenderId: '676079174860',
    projectId: 'carrot-market-clone-2c6e3',
    storageBucket: 'carrot-market-clone-2c6e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBMIy1t4k_X-ijzoERxpOwsvvTJWUEAaI',
    appId: '1:676079174860:ios:fd9903af8f73a510f96e69',
    messagingSenderId: '676079174860',
    projectId: 'carrot-market-clone-2c6e3',
    storageBucket: 'carrot-market-clone-2c6e3.appspot.com',
    iosClientId: '676079174860-0ul1s08b5lehmm45qd0p0cno0e6q2oke.apps.googleusercontent.com',
    iosBundleId: 'com.example.simpleMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBMIy1t4k_X-ijzoERxpOwsvvTJWUEAaI',
    appId: '1:676079174860:ios:fd9903af8f73a510f96e69',
    messagingSenderId: '676079174860',
    projectId: 'carrot-market-clone-2c6e3',
    storageBucket: 'carrot-market-clone-2c6e3.appspot.com',
    iosClientId: '676079174860-0ul1s08b5lehmm45qd0p0cno0e6q2oke.apps.googleusercontent.com',
    iosBundleId: 'com.example.simpleMarket',
  );
}
